% Hua-sheng Xie, huashengxie@gmail.com, CCF-ENN, 2019-06-13 11:00
% Draw FRC coil
close all; clear;clc;
run=['r=str2num(get(heditr,''String''));'...
    'z=str2num(get(heditz,''String''));'...
    'rw=str2num(get(heditrw,''String''));'...
    'zw=str2num(get(heditzw,''String''));'...
    'rl=str2num(get(heditrl,''String''));'...
    'zl=str2num(get(heditzl,''String''));'...
    'hl=str2num(get(hedithl,''String''));'...
    'wl=str2num(get(heditwl,''String''));'...
    'Il=str2num(get(heditIl,''String''));'...
    'Nl=str2num(get(heditNl,''String''));save(''frc_coil.mat'',''rl'',''zl'',''hl'',''wl'',''Il'',''Nl'');'...
    'imethod=get(hpopimethod,''value'');'...
    '[runtime,psi0,Br0,Bz0]=fun_frc_coil(r,z,rw,zw,rl,zl,hl,wl,Il,Nl,imethod,hAxes1,hAxes2,hAxes3);'...
    'set(heditBr,''String'',num2str(Br0));'...
    'set(heditBz,''String'',num2str(Bz0));'...
    'set(heditpsi,''String'',num2str(psi0));'...
    'set(heditB,''String'',num2str(sqrt(Br0^2+Bz0^2)));'];

savefig=['set(gcf,''PaperPositionMode'',''auto'');'...
    'print(gcf,''-dpng'',[''frc_Bfield_imethod='',num2str(imethod),''.png'']);'];


loaddat=['[filename,~]=uigetfile(''*.dat'');fid = fopen(filename);'...
    'set(heditr,''String'',fgetl(fid));'...
    'set(heditz,''String'',fgetl(fid));'...
    'set(heditrw,''String'',fgetl(fid));'...
    'set(heditzw,''String'',fgetl(fid));'...
    'set(heditrl,''String'',fgetl(fid));'...
    'set(heditzl,''String'',fgetl(fid));'...
    'set(hedithl,''String'',fgetl(fid));'...
    'set(heditwl,''String'',fgetl(fid));'...
    'set(heditIl,''String'',fgetl(fid));'...
    'set(heditNl,''String'',fgetl(fid));'...
    'fclose(fid);'
    ];
savedat=['[filename,pathname] = uiputfile(''*.dat'');'...
    'fid=fopen(filename,''w'');'...
    'fprintf(fid,''%s\n'',get(heditr,''String''));'...
    'fprintf(fid,''%s\n'',get(heditz,''String''));'...
    'fprintf(fid,''%s\n'',get(heditrw,''String''));'...
    'fprintf(fid,''%s\n'',get(heditzw,''String''));'...
    'fprintf(fid,''%s\n'',get(heditrl,''String''));'...
    'fprintf(fid,''%s\n'',get(heditzl,''String''));'...
    'fprintf(fid,''%s\n'',get(hedithl,''String''));'...
    'fprintf(fid,''%s\n'',get(heditwl,''String''));'...
    'fprintf(fid,''%s\n'',get(heditIl,''String''));'...
    'fprintf(fid,''%s\n'',get(heditNl,''String''));'...
    'fclose(fid);'
    ];

hf=figure('unit','normalized','Position',[-0.03 0.1 0.5 0.6],...
            'Name','FRC Coils Design and Magnetic Field',... % 'menubar','none',...
            'NumberTitle','off','DefaultAxesFontSize',14);
hAxes1=axes('unit','normalized','position',[0.07 0.65 0.72 0.3],...
        'Box','on');
hAxes2=axes('unit','normalized','position',[0.10 0.25 0.3 0.3],...
        'Box','on');
hAxes3=axes('unit','normalized','position',[0.50 0.25 0.3 0.3],...
        'Box','on');
    
htextin=uicontrol(hf,'unit','normalized','style','text','FontSize',12,...
               'position',[ 0.85 0.96 0.1 0.03],'max',2,'string','Input');    
htextr=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.92 0.04 0.03],'max',2,'string','r (m)'); 
heditr=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.89 0.92 0.06 0.03],'string','0.0');   
htextz=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.88 0.04 0.03],'max',2,'string','z (m)');
heditz=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.89 0.88 0.06 0.03],'string','0.0');
htextrw=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.84 0.04 0.03],'max',2,'string','rmax');
heditrw=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.89 0.84 0.06 0.03],'string','0.5');
htextzw=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.8 0.04 0.03],'max',2,'string','zmax');
heditzw=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.89 0.8 0.06 0.03],'string','1.5');

htextout=uicontrol(hf,'unit','normalized','style','text','FontSize',12,...
               'position',[ 0.85 0.76 0.1 0.03],'max',2,'string','Output');  
htextBr=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.73 0.04 0.03],'max',2,'string','Br(T)');
heditBr=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.89 0.73 0.06 0.03],'string','0.0');
htextBz=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.69 0.04 0.03],'max',2,'string','Bz(T)');
heditBz=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.89 0.69 0.06 0.03],'string','0.0');
htextB=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.65 0.04 0.03],'max',2,'string','B(T)');
heditB=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.89 0.65 0.06 0.03],'string','0.0');
htextpsi=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.61 0.04 0.03],'max',2,'string','psi(Wb)');
heditpsi=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.89 0.61 0.06 0.03],'string','0.0');

hpopimethod=uicontrol(hf,'unit','normalized','style','popup',...
            'position',[ 0.85 0.52 0.11 0.05],'String',{'method 1','method 2','method 3'});
htextrl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.03 0.12 0.05 0.04],'max',2,'string','r_l (m)');
heditrl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.08 0.12 0.25 0.05],'string','0.205,0.205,0.034,0.034,0.205,0.205');
        
htextzl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.34 0.12 0.07 0.04],'max',2,'string','z_l (m)');
heditzl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.41 0.12 0.25 0.05],'string','-1.50625,-0.73625,-0.57825,0.57825,0.73625,1.50625');
        %'-1.50625,-0.73625,-0.57825,0.57825,0.73625,1.50625'

htexthl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.03 0.05 0.05 0.04],'max',2,'string','h_l (m)');
hedithl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.08 0.05 0.25 0.05],'string','0.09,0.09,0.038,0.038,0.09,0.09');
        
htextwl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.34 0.05 0.07 0.04],'max',2,'string','w_l (m)');
heditwl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.41 0.05 0.25 0.05],'string','0.25,0.25,0.03,0.03,0.25,0.25');
        
htextIl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.67 0.12 0.05 0.04],'max',2,'string','I_l (A)');
heditIl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.72 0.12 0.25 0.05],'string','80,80,80,80,80,80');
        
htextNl=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.67 0.05 0.05 0.04],'max',2,'string','N_l (#)');
heditNl=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.72 0.05 0.25 0.05],'string','510,820,90,90,820,510');
        

hbloaddat=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.47 0.1 0.05],...
                'String','Load Data',...
                'Callback',loaddat);         
hbsavedat=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.42 0.1 0.05],...
                'String','Save Data',...
                'Callback',savedat); 
            
hbrun=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.3 0.1 0.05],...
                'String','Run',...
                'Callback',run); 
hbsavefig=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.25 0.1 0.05],...
                'String','Save Fig',...
                'Callback',savefig); 
            
hbexit=uicontrol(hf,'style','push',...
               'unit','normalized','position',[0.85 0.2 0.1 0.05],...
               'callback','close',...
               'string','Exit');